#!/usr/bin/python3
print(" ____        _  _______  _______ ")
print("| __ )  ___ | ||_   _\ \/ /_   _|")
print("|  _ \ / _ \| __|| |  \  /  | |  ")
print("| |_) | (_) | |_ | |  /  \  | |  ")
print("|____/ \___/ \__||_| /_/\_\ |_|")
print()
print("\033[;36m"+"Creado por S3RGI09 (Sergio Casero Verdial)")
print("\033[;35m"+"Script para crear el archivo robots.txt")

Web= input("\033[1;32m"+"Introduce la URL: "+'\033[0;m') 
print("\033[;34m"+"Copia desde aqui hasta abajo"+'\033[0;m')
print("# robots.txt generate by BotTXT")
print("User-agent: Applebot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: baiduspider")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Bingbot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: DuckDuckBot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Googlebot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Twitterbot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Yeti")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: *")
print("Disallow: /cgi-bin/")
print("Sitemap: "+ Web)
print("\033[1;31m"+"-------------------------------------------------")
print("\033[1;31m"+"Copie aqui el texto de arriba y peguelo en su web")
