Web= input("Introduce la URL ") 
print("# Robots.txt generate by PyBotTXT.py")
print("User-agent: Applebot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: baiduspider")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Bingbot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: DuckDuckBot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Googlebot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Twitterbot")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: Yeti")
print("Disallow: /publicapi/")
print("Disallow: /query/")
print("Disallow: /logging/")
print("Disallow: /qp/batch_fetch_web/")
print("Disallow: /client_error/")
print("Disallow: /*__a=1*")
print("")
print("User-agent: *")
print("Disallow: /cgi-bin/")
print("Sitemap: "+ Web)
